name: Build

on:
  # push:
  #   tags-ignore: # Exclude the release tags since they trigger a dedicated build action.
  #     - 'v[0-9]+.[0-9]+'
  #     - 'v[0-9]+.[0-9]+-dockerupdate-[0-9]+'
  #     - 'v[0-9]+.[0-9]+.[0-9]+'
  #     - 'v[0-9]+.[0-9]+.[0-9]+-dockerupdate-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build .
