name: Tests

on:
  push:

env:
  TZ: Europe/Amsterdam

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-20.04
    timeout-minutes: 300

    steps:
    - name: Checkout docker-languagetool
      uses: actions/checkout@v2

    - name: Build
      run: docker build --target=build -t languagetool-build .

    - name: Run tests
      run: docker run -e "MAVEN_OPTS=-Xmx2048m" languagetool-build mvn test --projects languagetool-standalone
