name: Tests

on:
  push:
    paths:
      - Dockerfile
      - arm64-workaround/**
    tags-ignore: # Exclude the release tags since they trigger a dedicated release action.
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-dockerupdate-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dockerupdate-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download
      run: docker build --target=build -t languagetool-build .
    - name: Run tests
      run: docker run languagetool-build mvn --projects languagetool-standalone clean test --also-make --quiet --errors